# Database configuration
db_host: "87.239.109.143"
db_name: "leskina_test_database"
db_user: "appuser"
db_password: "SecureDBpass123!"  # Замените на реальный пароль

# Application configuration
app_port: 8000
app_directory: "/opt/app"

# Internal IPs for load balancing
internal_ips:
  haproxy: "192.168.100.10"
  app_server_1: "192.168.100.20"
  app_server_2: "192.168.100.21"